# Import Numpy

In [3]:
import numpy as np

my_list = [1,2,3,4]

type(np.array(my_list))
arr = np.array(my_list)
arr

array([1, 2, 3, 4])

# Arange()


In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Vector Addition

In [10]:
print("Current Array :",arr)
a1 = arr+arr
a1

Current Array : [1 2 3 4 5 6]


array([ 2,  4,  6,  8, 10, 12])

# Multiplication

In [13]:
print("Current Array :",arr)

print("********After Multiplication*********")
a2 = 2*arr
a2

Current Array : [1 2 3 4 5 6]
********After Multiplication*********


array([ 2,  4,  6,  8, 10, 12])

# Power

In [15]:
print("Current Array :",arr)
print("********After power*********")
a3 = arr**2
a3

Current Array : [1 2 3 4 5 6]
********After power*********


array([ 1,  4,  9, 16, 25, 36], dtype=int32)

# Square Root

In [18]:
print("Current Array :",arr)
print("********After Square Root*********")
np.sqrt(arr)

Current Array : [1 2 3 4 5 6]
********After Square Root*********


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

# Log Value

In [21]:
print("Current Array :",arr)
print("********After Log*********")
np.log(arr)

Current Array : [1 2 3 4 5 6]
********After Log*********


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

# 0's Matrix

In [24]:
# it will always genrate float value
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 1's Matrix

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Random number matrix

In [44]:
np.random.randint(0,10)

5

# Random number Matrix 

In [53]:
np.random.randint(0,100,(4,4))

array([[73, 54, 71, 16],
       [14, 70,  8, 53],
       [74, 38, 80, 66],
       [45, 92, 41, 29]])

# Random number By using seed()

In [64]:
# It will always genrate same number again and again
np.random.seed(101)

np.random.randint(0,100,(4,4))

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

# To check min and max value

In [78]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

print("Array Value :",arr)

print("Maximum Value :",arr.max())

print("Minimum Value :",arr.min())


Array Value : [95 11 81 70 63 87 75  9 77 40]
Maximum Value : 95
Minimum Value : 9


# To calculate Average

In [81]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

print("Array Value :",arr)

print("Average :",arr.mean())

Array Value : [95 11 81 70 63 87 75  9 77 40]
Average : 60.8


# Argmax() : to find max value index number

In [84]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

print("Array Value :",arr)
arr.argmax()# (95)

Array Value : [95 11 81 70 63 87 75  9 77 40]


0

# Argmin() : to find min value index number

In [86]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

print("Array Value :",arr)
arr.argmin()# (9)

Array Value : [95 11 81 70 63 87 75  9 77 40]


7

# Reshape(): to reshape of array into matrix

In [91]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

print("Array Value :",arr)
arr.reshape(2,5)

Array Value : [95 11 81 70 63 87 75  9 77 40]


array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

# Slicing

In [100]:
mat = np.arange(0,100).reshape(10,10)
print("Current MAtrix :",mat)


print("************ To find only row***********")
mat[0,:]

print("************ To find only Column***********")
mat[:,0] #col

Current MAtrix : [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
************ To find only row***********
************ To find only Column***********


array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# to genrate row==col

In [102]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])